name: Build and Publish Go projects

on:
  workflow_dispatch:

jobs:
  log_context_values:
    runs-on: ubuntu-latest
    steps:
      - name: Log Github Context
        id: github_context-step
        run: echo '${{ toJSON(github) }}'